@startuml 全体概要図

skinparam packageStyle Frame

interface ベースオブジェクト{
	名称
	説明
	..
}

class スキル
スキル #..^ ベースオブジェクト
class 異常状態
異常状態 #..^ ベースオブジェクト
class 部位{
	..
	対応スキル
}
部位 #..^ ベースオブジェクト
部位 *-- スキル
class スキルセット{
	対応値
	..
}
スキルセット #..^ スキル
class ジョブ{
	..
	条件スキルセットリスト
}
ジョブ #..^ ベースオブジェクト
ジョブ o-- スキルセット

interface エンティティ{
	ID
	..
}

class 属性
属性 #..^ ベースオブジェクト
interface 属性付き{
	..
	属性リスト
	..
	主要属性
}
属性付き o-- 属性

namespace アビリティ{
	entity アビリティルート{
		..
	}
	abstract アビリティ雛形{
		..
		対応スキルセットリスト
		所要部位リスト
		動作リスト
	}

	.アビリティルート #--^ アビリティ雛形
	アビリティ雛形 #..^ .ベースオブジェクト
	アビリティ雛形 o-- .部位
	アビリティ雛形 o-- .スキルセット

	class 動作
	アビリティ雛形 o-- 動作
}
アビリティルート #..^ エンティティ
アビリティルート #..^ 属性付き

namespace アイテム{
	entity アイテムルート
	abstract アイテム雛形{
		..
		装備可能部位
	}

	.アイテムルート #--^ アイテム雛形
	アイテム雛形 #..^ .ベースオブジェクト
	アイテム雛形 o-- .部位
}
アイテムルート #..^ エンティティ
アイテムルート #..^ 属性付き

namespace 地域{
	entity 地域ルート{
		..
		マップリスト
	}
	abstract 地域雛形{
		..
		地形
		イベントリスト
	}
	class 地形
	class イベント
	entity マップ{
		..
		発生イベント
		地形リスト
	}
	.マップ o-- 地形
	.マップ *-- イベント

	.地域ルート #--^ 地域雛形
	地域雛形 #..^ .ベースオブジェクト
	地域雛形 o-- 地形
	地域雛形 o-- イベント
	.地域ルート o-- .マップ
}
地域ルート #..^ エンティティ
地域ルート #..^ 属性付き

namespace キャラクタ{
	abstract キャラクタ雛形{
		..
		スキルリスト
		習得アビリティリスト
		所持アイテムリスト
		部位リスト
		状態リスト
	}

	キャラクタ雛形 #..^ .ベースオブジェクト
	キャラクタ雛形 o-- .部位
	class 装備枠
	(キャラクタ雛形,.部位) *- 装備枠
	装備枠 *-- アイテム

	entity Player
	.Player #..^ キャラクタ雛形

	entity NPC{
		..
		行動アルゴリズム
		追加習得アビリティリスト
		追加所持アイテムリスト
	}
	.NPC #..^ .属性付き
	.NPC #..^ キャラクタ雛形

	class 行動条件
	class 行動パターン
	class 行動要素
	.NPC o-- 行動条件
	行動条件 *-- 行動パターン
	行動パターン o-- 行動要素
}
キャラクタ.キャラクタ雛形 #..^ エンティティ
キャラクタ.キャラクタ雛形 o- スキル
キャラクタ.キャラクタ雛形 o- アビリティ
キャラクタ.キャラクタ雛形 o- 異常状態
キャラクタ.キャラクタ雛形 o- アイテム


class 探索制御 <<(S,orange)>>{
	地域生成
	マップリンク生成
	マップリンク管理
	マップ生成
	属性割り当て
	地形割り当て
	イベント割り当て
}
探索制御 +-- .地域ルート : 生成
探索制御 +-- 地域 : 取得

class アビリティ管理 <<(S,orange)>>{
	アビリティ生成
	属性割り当て
	アビリティ習得
	アビリティ削除
	アビリティ使用
}
アビリティ管理 +-- アビリティルート : 生成

class アイテム管理 <<(S,orange)>>{
	アイテム生成
	属性割り当て
	アイテム習得
	アイテム削除
	アイテム利用
}
アイテム管理 +-- アイテムルート : 生成
キャラクタ +--> アイテム管理 : 利用
キャラクタ +--> アビリティ管理 : 利用

class キャラクタ管理 <<(S,orange)>>{
	キャラクタ生成
	属性割り当て
	状態制御
}
キャラクタ管理 +-- .NPC : 生成
キャラクタ管理 +-- キャラクタ : 状態制御

class ローグライク動作制御 <<(S,orange)>>{
	行動決定
	行動結果演算・格納
	行動結果表示
}
ローグライク動作制御 +-> キャラクタ管理 : 生成、制御
ローグライク動作制御 +--> アイテム管理 : 生成、入手、削除
ローグライク動作制御 +--> アビリティ管理 : 生成、習得
ローグライク動作制御 +--> 探索制御 : マップ読み込み、地形読み込み

class セーブデータ管理 <<(S,orange)>>{
	セーブデータ保存
	セーブデータ読み出し・反映
}
セーブデータ管理 +-- 地域 : 反映
セーブデータ管理 +-- キャラクタ : 反映

class 中央制御システム <<(S,orange)>>{
	プレイヤー生成
	地域生成
	メインルーチン
	セーブデータ制御
}
中央制御システム +--> 探索制御 : 生成、制御
中央制御システム +--> キャラクタ管理 : 生成
中央制御システム +--> ローグライク動作制御 : 制御
中央制御システム +--> セーブデータ管理 : 生成・読み込み


@enduml
