@startuml 全体概要図

skinparam packageStyle Frame

abstract 名前付き{
	名称
	説明
	..
}

class スキル
スキル #..^ 名前付き
enum スキルリスト
スキルリスト +-> スキル
class 異常状態
異常状態 #..^ 名前付き
class 部位{
	..
	対応スキル
}
部位 #..^ 名前付き
部位 *-- スキル
class スキルセット{
	対応値
	..
}
スキルセット #..^ スキル

class ジョブ{
	..
	条件スキルセットリスト
}
ジョブ #..^ 名前付き
ジョブ o-- スキルセット
enum ジョブリスト
ジョブリスト +--> ジョブ

class 形容詞
enum 形容詞リスト
形容詞リスト +-> 形容詞
形容詞 #..^ 名前付き
interface 形容詞付き{
	{abstract}形容詞と特性の対応リスト
	{abstract}特性パラメータ
	..
	形容詞リスト
	..
	主要形容詞取得()
}
形容詞付き o-- 形容詞
形容詞付き +--> 形容詞リスト

namespace アビリティ{
	entity アビリティルート{
		..
	}
	abstract アビリティ雛形{
		..
		対応スキルセットリスト
		所要部位リスト
		動作リスト
		習得条件
	}

	enum アビリティ雛形リスト
	アビリティ雛形リスト +-> アビリティ雛形

	.アビリティルート #--^ アビリティ雛形
	アビリティ雛形 #..^ .名前付き
	アビリティ雛形 o-- .部位
	アビリティ雛形 o-- .スキルセット
	アビリティ雛形 o-- .ジョブ

	class 動作
	アビリティ雛形 o-- 動作
	動作 #..^ .名前付き

	enum 動作リスト
	動作リスト +-> 動作
}
アビリティルート #..^ 形容詞付き

namespace アイテム{
	entity アイテムルート
	abstract アイテム雛形{
		..
		装備可能部位
		使用条件
	}

	enum アイテム雛形リスト
	アイテム雛形リスト +-> アイテム雛形

	.アイテムルート #--^ アイテム雛形
	アイテム雛形 #..^ .名前付き
	アイテム雛形 o-- .部位
	アイテム雛形 o-- .ジョブ
}
アイテムルート #..^ 形容詞付き

namespace 地域{
	entity 地域ルート{
		..
		コネクションリスト
		マップリスト
		..
		マップ生成()
	}
	abstract 地域雛形{
		..
		マップチップリスト
		イベントリスト
	}
	class マップチップ{
		地形リスト
		..
	}
	class 地形
	マップチップ o-- 地形
	地形 #..^ .名前付き
	class イベント
	entity マップ{
		地域内座標
		..
		発生イベント
		座標・マップチップ対応リスト
		座標・キャラクタ対応リスト
	}
	.マップ o-- マップチップ
	.マップ *-- イベント
	entity コネクション{
		地域内座標
		接続先地域
		..
	}

	enum マップチップリスト
	マップチップリスト +-> マップチップ

	.地域ルート #--^ 地域雛形
	地域雛形 #..^ .名前付き
	地域雛形 o-- マップチップ
	地域雛形 o-- イベント
	.地域ルート o-- .マップ
	.地域ルート o-- .コネクション
}
地域ルート #..^ 形容詞付き
.マップ o-- キャラクタ
.コネクション *- 世界地図

namespace キャラクタ{
	abstract キャラクタ雛形{
		..
		スキルリスト
		習得アビリティリスト
		所持アイテムリスト
		部位リスト
		状態リスト
		ジョブリスト
		行動アルゴリズム
	}

	キャラクタ雛形 #..^ .名前付き
	キャラクタ雛形 o-- .部位
	キャラクタ雛形 o-- .ジョブ
	class 装備枠
	(キャラクタ雛形,.部位) *- 装備枠
	装備枠 *-- アイテム

	entity Player
	.Player #..^ キャラクタ雛形

	entity NPC{
		..
		追加習得アビリティリスト
		追加所持アイテムリスト
		追加行動アルゴリズム
	}
	.NPC #..^ .形容詞付き
	.NPC #..^ キャラクタ雛形

	enum キャラクタ雛形リスト
	キャラクタ雛形リスト +-> キャラクタ雛形

	class 行動条件
	class 行動パターン
	class 行動要素
	.NPC o-- 行動条件
	キャラクタ雛形 o- 行動条件
	行動条件 *-- 行動パターン
	行動パターン o-- 行動要素

	enum 行動条件リスト
	行動条件リスト +--> 行動条件

	enum 行動パターンリスト
	行動パターンリスト +-> 行動パターン
}
キャラクタ.キャラクタ雛形 o- スキル
キャラクタ.キャラクタ雛形 o- アビリティ
キャラクタ.キャラクタ雛形 o- 異常状態
キャラクタ.キャラクタ雛形 o- アイテム

enum 世界地図{
	地域リスト
}

世界地図 +--> 地域

class 探索制御 <<(S,orange)>>{
	地域生成
	マップ生成
	形容詞割り当て
	地形割り当て
	イベント割り当て
}
探索制御 +-- .地域ルート : 生成
探索制御 +-- 世界地図 : 取得

class キャラクタ管理 <<(S,orange)>>{
	キャラクタ生成
	形容詞割り当て
	状態制御
}
キャラクタ管理 +-- .NPC : 生成
キャラクタ管理 +-- キャラクタ : 状態制御

class アビリティ管理 <<(S,orange)>>{
	アビリティ生成
	形容詞割り当て
	アビリティ習得
	アビリティ削除
	アビリティ使用
}
アビリティ管理 +-- アビリティルート : 生成
アビリティ管理 +--> キャラクタ管理 : 習得・削除

class アイテム管理 <<(S,orange)>>{
	アイテム生成
	形容詞割り当て
	アイテム習得
	アイテム削除
	アイテム利用
}
アイテム管理 +-- アイテムルート : 生成
アイテム管理 +--> キャラクタ管理 : 取得・削除
キャラクタ +--> アイテム管理 : 利用
キャラクタ +--> アビリティ管理 : 利用

class ローグライク動作制御 <<(S,orange)>>{
	行動決定
	行動結果演算・格納
	行動結果表示
}
ローグライク動作制御 +-> キャラクタ管理 : 生成、制御
ローグライク動作制御 +--> アイテム管理 : 生成、入手、削除
ローグライク動作制御 +--> アビリティ管理 : 生成、習得
ローグライク動作制御 +--> 探索制御 : マップ読み込み、地形読み込み

class セーブデータ管理 <<(S,orange)>>{
	セーブデータ保存
	セーブデータ読み出し・反映
}
セーブデータ管理 +-- 世界地図 : 反映
セーブデータ管理 +-- キャラクタ : 反映

class 描画管理 <<(S,orange)>>{
	マップ状況反映
	エフェクト発生
}
ローグライク動作制御 +--> 描画管理 : マップ状況反映

class 中央制御システム <<(S,orange)>>{
	プレイヤー生成
	地域生成
	メインルーチン
	セーブデータ制御
}
中央制御システム +--> 探索制御 : 生成、制御
中央制御システム +--> キャラクタ管理 : 生成
中央制御システム +--> ローグライク動作制御 : 制御
中央制御システム +--> セーブデータ管理 : 生成・読み込み
中央制御システム +--> Player : 制御

@enduml
