@startuml 全体概要図

skinparam packageStyle Frame

interface ベースオブジェクト{
	名称
	説明
	..
}

class スキル
スキル #..^ ベースオブジェクト
class 状態
状態 #..^ ベースオブジェクト
class 部位{
	..
	対応スキル
}
部位 #..^ ベースオブジェクト
部位 *-- スキル
class スキルセット{
	対応値
	..
}
スキルセット #..^ スキル
class ジョブ{
	..
	条件スキルセットリスト
}
ジョブ #..^ ベースオブジェクト
ジョブ o-- スキルセット

interface エンティティ{
	ID
	..
}

class 属性
属性 #..^ ベースオブジェクト
interface 属性付き{
	..
	属性リスト
	..
	主要属性
}
属性付き o-- 属性

namespace アビリティ{
	entity アビリティルート{
		..
	}
	abstract アビリティ雛形{
		..
		対応スキルセットリスト
		所要部位リスト
		動作リスト
	}

	.アビリティルート #--^ アビリティ雛形
	アビリティ雛形 #..^ .ベースオブジェクト
	アビリティ雛形 o-- .部位
	アビリティ雛形 o-- .スキルセット

	class 動作
	アビリティ雛形 o-- 動作
}
アビリティルート #..^ エンティティ
アビリティルート #..^ 属性付き

namespace アイテム{
	entity アイテムルート
	abstract アイテム雛形{
		..
		装備可能部位
	}

	.アイテムルート #--^ アイテム雛形
	アイテム雛形 #..^ .ベースオブジェクト
	アイテム雛形 o-- .部位
}
アイテムルート #..^ エンティティ
アイテムルート #..^ 属性付き

class 地形
class イベント
entity マップ
マップ o-- 地形
マップ *-- イベント
namespace 地域{
	entity 地域ルート{
		..
		マップリスト
	}
	abstract 地域雛形{
		..
		地形
		イベントリスト
	}

	.地域ルート #--^ 地域雛形
	地域雛形 #..^ .ベースオブジェクト
	地域雛形 o-- .地形
	地域雛形 o-- .イベント
	.地域ルート o-- .マップ
}
地域ルート #..^ エンティティ
地域ルート #..^ 属性付き

namespace キャラクタ{
	abstract キャラクタ雛形{
		..
		スキルリスト
		習得アビリティリスト
		所持アイテムリスト
		部位リスト
		状態リスト
	}

	キャラクタ雛形 #..^ .ベースオブジェクト
	キャラクタ雛形 o-- .部位
	class 装備枠
	(キャラクタ雛形,.部位) *- 装備枠
	装備枠 *-- アイテム

	entity Player
	.Player #..^ キャラクタ雛形

	entity NPC{
		..
		行動アルゴリズム
		追加習得アビリティリスト
		追加所持アイテムリスト
	}
	.NPC #..^ .属性付き
	.NPC #..^ キャラクタ雛形

	class 行動条件
	class 行動パターン
	class 行動要素
	.NPC o-- 行動条件
	行動条件 *-- 行動パターン
	行動パターン o-- 行動要素
}
キャラクタ.キャラクタ雛形 #..^ エンティティ
キャラクタ.キャラクタ雛形 o- スキル
キャラクタ.キャラクタ雛形 o- アビリティ
キャラクタ.キャラクタ雛形 o- 状態
キャラクタ.キャラクタ雛形 o- アイテム

@enduml
